/**
 * The provider port.
 *
 * This is the single seam between the orchestrator and any AI vendor. The
 * orchestrator imports THIS file and never an SDK, so adding OpenAI, Anthropic
 * or Gemini later is a matter of writing one adapter that satisfies
 * `AIProvider` and registering it — no orchestrator change.
 */

import type { AgentId } from './types.ts';

export type ProviderId = 'mock' | 'openai' | 'anthropic' | 'gemini' | 'openai-compatible';

/**
 * `available` — implemented and usable right now.
 * `planned`   — the adapter exists as a typed stub and throws
 *               ProviderNotConfiguredError if executed. It is listed by the API
 *               so the UI can show what is coming without pretending it works.
 */
export type ProviderAvailability = 'available' | 'planned';

export interface ProviderModel {
  id: string;
  label: string;
  /** Context window in tokens, when the vendor publishes one. */
  contextWindow?: number;
}

/** Output of an agent that already ran, handed to downstream agents. */
export interface UpstreamResult {
  agentId: AgentId;
  name: string;
  result: string;
}

/** An agent that failed, so QA and the Integrator can account for the gap. */
export interface FailedAgent {
  agentId: AgentId;
  name: string;
  error: string;
}

/**
 * Structured context behind the rendered prompt.
 *
 * `ProviderTask.prompt` is the fully rendered text a real vendor adapter sends.
 * `context` is the same information before rendering, which lets an adapter use
 * a vendor's native structure (multi-turn messages, tool results, cache
 * breakpoints) instead of re-parsing a string. Adapters that do not need it
 * simply ignore it and send `prompt`.
 */
export interface TaskContext {
  missionPrompt: string;
  upstream: readonly UpstreamResult[];
  failed: readonly FailedAgent[];
}

/** A single unit of work handed to a provider. */
export interface ProviderTask {
  /** Which agent this call is on behalf of; adapters may use it for routing. */
  agentId: AgentId;
  /** Persona + instructions. */
  systemPrompt: string;
  /** The actual request, already assembled with upstream agent context. */
  prompt: string;
  /** The same information, unrendered. Optional for adapters that ignore it. */
  context?: TaskContext;
  model: string;
  temperature?: number;
  maxTokens?: number;
  /** Correlation data for logs and tracing. Never sent to a vendor verbatim. */
  metadata?: Record<string, string>;
}

/** The normalised shape every adapter must return, whatever the vendor sends. */
export interface ProviderResult {
  provider: ProviderId;
  model: string;
  text: string;
  usage: ProviderUsage;
  /** Vendor request id when available, otherwise one generated by the adapter. */
  requestId: string;
  finishReason: 'stop' | 'length' | 'content_filter' | 'other';
  latencyMs: number;
}

export interface ProviderUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

export interface AIProvider {
  readonly id: ProviderId;
  readonly label: string;
  readonly availability: ProviderAvailability;
  /** Models this adapter accepts; the first is the default. */
  listModels(): readonly ProviderModel[];
  /**
   * Execute one task. Implementations must:
   *  - honour `signal` and abort promptly,
   *  - throw a `ProviderFailedError` (or subclass) on vendor failure,
   *  - never throw a raw vendor error type across this boundary.
   */
  execute(task: ProviderTask, signal?: AbortSignal): Promise<ProviderResult>;
}

/** Read-only view of a provider, safe to expose over the API. */
export interface ProviderDescriptor {
  id: ProviderId;
  label: string;
  availability: ProviderAvailability;
  models: readonly ProviderModel[];
  /** Why a `planned` provider is not usable yet. */
  note?: string;
}

export function describeProvider(provider: AIProvider, note?: string): ProviderDescriptor {
  return {
    id: provider.id,
    label: provider.label,
    availability: provider.availability,
    models: provider.listModels(),
    ...(note !== undefined ? { note } : {}),
  };
}
